version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 
  heroku: circleci/heroku@1.2.2
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          requires:
            - build
          filters:
            branches:
              only: auto_deploy
      
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: sample_app
          RAILS_ENV: test
      - image: postgres:10.14
        environment:
          POSTGRES_USER: sample_app
          POSTGRES_DB: sample_app_test
          POSTGRES_PASSWORD: "2222"
    executor: ruby/default
    steps:
      - checkout
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Which bundler?
          command: bundle -v

      - restore_cache:
            keys:
              # when lock file changes, use increasingly general patterns to restore cache
              - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
              - gem-cache-v1-{{ arch }}-{{ .Branch }}
              - gem-cache-v1

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: yarn add webpack-cli
      - run: bundle exec rake webpacker:compile
      - run: bundle exec rake assets:precompile

      - run: bundle exec rails db:create
      - run: bundle exec rails db:migrate
      - run: bundle exec rspec
      - run: bundle exec rubocop
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master